ArticlProject/Controllers/AuthorController.cs
using ArticlProject.Core;
using ArticlProject.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace ArticlProject.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IDataHelper<Author> dataHelper;
        private readonly IAuthorizationService authorizationService;
        private readonly IWebHostEnvironment webHost;
        private readonly Code.FilesHelper filesHelper;
        private int pageItem;
        public AuthorController(
            IDataHelper<Author> dataHelper,
            IAuthorizationService authorizationService
            , IWebHostEnvironment webHost)
        {
            this.dataHelper = dataHelper;
            this.authorizationService = authorizationService;
            this.webHost = webHost;
            filesHelper = new Code.FilesHelper(this.webHost);
            pageItem = 10;
        }

        // GET: AuthorController
        [Authorize("Admin")]
        public ActionResult Index(int? id)
        {
            if (id == 0 || id == null)
            {
                return View(dataHelper.GetAllData().Take(pageItem));
            }
            else
            {
                var data = dataHelper.GetAllData().Where(x => x.Id > id).Take(pageItem);
                return View(data);
            }
        }
        [Authorize("Admin")]
        public ActionResult Search(string SearchItem)
        {
            if (SearchItem == null)
            {
                return View("Index", dataHelper.GetAllData());
            }
            else
            {
                return View("Index", dataHelper.Search(SearchItem));

            }
        }
        // GET: AuthorController/Edit/5
        [Authorize]

        public ActionResult Edit(int id)
        {
            var author = dataHelper.Find(id);
            CoreView.AuthorView authorView = new CoreView.AuthorView
            {
                Id = author.Id,
                Bio = author.Bio,
                Facbook = author.Facbook,
                FullName = author.FullName,
                Instagram = author.Instagram,
                Twitter = author.Twitter,
                UserId = author.UserId,
                UserName = author.UserName,
            };
            return View(authorView);
        }

        // POST: AuthorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, CoreView.AuthorView collection)
        {
            try
            {
                var author = new Author
                {
                    Id = collection.Id,
                    Bio = collection.Bio,
                    Facbook = collection.Facbook,
                    FullName = collection.FullName,
                    Instagram = collection.Instagram,
                    Twitter = collection.Twitter,
                    UserId = collection.UserId,
                    UserName = collection.UserName,
                    ProfileImageUrl = filesHelper.UploadFile(collection.ProfileImageUrl, "Images")

                };
                dataHelper.Edit(id, author);

                var result = authorizationService.AuthorizeAsync(User, "Admin");
                if (result.Result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    return Redirect("/AdminIndex");
                }
            }
            catch 
            {
                return View();
            }
        }

        // GET: AuthorController/Delete/5
        [Authorize("Admin")]
        public ActionResult Delete(int id)
        {
            var author = dataHelper.Find(id);
            CoreView.AuthorView authorView = new CoreView.AuthorView
            {
                Id = author.Id,
                Bio = author.Bio,
                Facbook = author.Facbook,
                FullName = author.FullName,
                Instagram = author.Instagram,
                Twitter = author.Twitter,
                UserId = author.UserId,
                UserName = author.UserName,
            };
            return View(authorView);
        }

        // POST: AuthorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize("Admin")]
        public ActionResult Delete(int id, Author collection)
        {
            try
            {
                dataHelper.Delete(id);
                string filePath = "~/Images/" + collection.ProfileImageUrl;
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ArticlProject/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html style="font-family: Cairo, sans-serif;">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - مقالتي</title>
    <meta name="description" content="موقع يسمح لك بنشر مقالات ومشاركتها مع الاخرين">
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cairo&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/css/Animation-Cards-1.css">
    <link rel="stylesheet" href="~/css/Animation-Cards.css">
    <link rel="stylesheet" href="~/css/Article-Cards.css">
    <link rel="stylesheet" href="~/css/Article-Clean.css">
    <link rel="stylesheet" href="~/css/Article-List.css">
    <link rel="stylesheet" href="~/css/Black-Navbar.css">
    <link rel="stylesheet" href="~/css/dh-card-image-left-dark.css">
    <link rel="stylesheet" href="~/css/dh-navbar-inverse.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="~/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="~/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="~/css/Navbar---Apple-1.css">
    <link rel="stylesheet" href="~/css/Navbar---Apple.css">
    <link rel="stylesheet" href="~/css/Navigation-with-Button.css">
    <link rel="stylesheet" href="~/css/Navigation-with-Search.css">
    <link rel="stylesheet" href="~/css/News-Cards.css">
    <link rel="stylesheet" href="~/css/Off-Canvas-Sidebar-Drawer-Navbar.css">
    <link rel="stylesheet" href="~/css/Responsive-UI-Card-02.css">
    <link rel="stylesheet" href="~/css/Right-Sidebar.css">
    <link rel="stylesheet" href="~/css/Sidebar-Menu-1.css">
    <link rel="stylesheet" href="~/css/Sidebar-Menu.css">
    <link rel="stylesheet" href="~/css/SIdebar-Responsive-2-1.css">
    <link rel="stylesheet" href="~/css/SIdebar-Responsive-2.css">
    <link rel="stylesheet" href="~/css/Sidebar-right-opening.css">
    <link rel="stylesheet" href="~/css/Social-Icons.css">
    <link rel="stylesheet" href="~/css/Soft-UI-Aside-Navbar.css">
    <link rel="stylesheet" href="~/css/Studious-sidebar.css">
    <link rel="stylesheet" href="~/css/Team-Boxed.css">
    <link rel="stylesheet" href="~/css/Vertical-Left-SideBar-by-Jigar-Mistry.css">
    @*
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@
</head>

<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="72">
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-secondary text-uppercase" id="mainNav" style="font-family: Cairo, sans-serif;">
        <div class="container">
            <a class="navbar-brand" href="index.html" style="font-family: Cairo, sans-serif;">مقالاتي</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler text-white bg-primary navbar-toggler-right text-uppercase rounded" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
            <div class="collapse navbar-collapse text-center" id="navbarResponsive">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about" style="font-family: Cairo, sans-serif;">من نحن؟</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact" style="font-family: Cairo, sans-serif;">تواصل معنا</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="/AllUsers" style="font-family: Cairo, sans-serif;">الناشرون</a></li>
                    <li class="nav-item mx-0 mx-lg-1"></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="index.html" style="font-family: Cairo, sans-serif;">الرئيسة</a></li>
                    <li class="nav-item mx-0 mx-lg-1"></li>
                </ul>
               
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="btn btn-primary" role="button" style="font-family: Cairo, sans-serif;" href="/AdminIndex">لوحة التحكم</a>
                }

            </div>
        </div>
    </nav>




    <div class="container" style=" font-family:Cairo;direction:rtl">
        @RenderBody()
    </div>


    <footer class="text-center footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4" style="font-family: Cairo, sans-serif;">موقعنا</h4>
                    <p style="font-family: Cairo, sans-serif;">Clark, MO 65243</p>
                </div>
                <div class="col-md-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase" style="font-family: Cairo, sans-serif;">تابعنا لتكون قريب منا</h4>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a class="btn btn-outline-light text-center btn-social rounded-circle" role="button" href="#"><i class="fa fa-facebook fa-fw"></i></a></li>
                        <li class="list-inline-item"><a class="btn btn-outline-light text-center btn-social rounded-circle" role="button" href="#"><i class="fa fa-google-plus fa-fw"></i></a></li>
                        <li class="list-inline-item"><a class="btn btn-outline-light text-center btn-social rounded-circle" role="button" href="#"><i class="fa fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a class="btn btn-outline-light text-center btn-social rounded-circle" role="button" href="#"><i class="fa fa-dribbble fa-fw"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4 class="text-uppercase mb-4" style="font-family: Cairo, sans-serif;">من نحن ؟</h4>
                    <p class="lead mb-0"><span style="font-family: Cairo, sans-serif;">نتيح لك نشر مقالات مع حفظ كامل الحقوق&nbsp;</span></p>
                </div>
            </div>
        </div>
    </footer>
    <div class="text-center text-white copyright py-4">
        <div class="container"><small style="font-family: Cairo, sans-serif;">Copyright ©&nbsp;مقالتي 2022</small></div>
    </div>
    <div class="d-lg-none scroll-to-top position-fixed rounded"><a class="text-center d-block rounded text-white" href="#page-top"><i class="fa fa-chevron-up"></i></a></div>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/bs-init-1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="~/js/Off-Canvas-Sidebar-Drawer-Navbar.js"></script>
    <script src="~/js/freelancer.js"></script>
    <script src="~/js/Off-Canvas-Sidebar-Drawer-Navbar-1.js"></script>
    <script src="~/js/Studious-sidebar.js"></script>
    <script src="~/js/bs-init.js"></script>
    <script src="~/js/chart.min.js"></script>
    <script src="~/js/Navbar---Apple.js"></script>
    <script src="~/js/Right-Sidebar.js"></script>
    <script src="~/js/Sidebar-Menu.js"></script>
    <script src="~/js/Sidebar-right-opening.js"></script>
    <script src="~/js/theme.js"></script>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@

    @RenderSection("Scripts", required: false)

</body>

</html>

ArticlProject/Pages/Shared/_LayoutAdmin.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@inject ArticlProject.Data.IDataHelper<ArticlProject.Core.Author> datahelper
@{
    var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
    int id = datahelper.GetAllData().Where(x => x.UserId == userid).Select(x => x.Id).First();
    var result = AuthorizationService.AuthorizeAsync(User, "Admin");

}
<!DOCTYPE html>
<html style="font-family: Cairo, sans-serif;">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>مقالتي</title>
    <meta name="description" content="موقع يسمح لك بنشر مقالات ومشاركتها مع الاخرين">
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cairo&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/css/Animation-Cards-1.css">
    <link rel="stylesheet" href="~/css/Animation-Cards.css">
    <link rel="stylesheet" href="~/css/Article-Cards.css">
    <link rel="stylesheet" href="~/css/Article-Clean.css">
    <link rel="stylesheet" href="~/css/Article-List.css">
    <link rel="stylesheet" href="~/css/Black-Navbar.css">
    <link rel="stylesheet" href="~/css/dh-card-image-left-dark.css">
    <link rel="stylesheet" href="~/css/dh-navbar-inverse.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="~/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="~/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="~/css/Navbar---Apple-1.css">
    <link rel="stylesheet" href="~/css/Navbar---Apple.css">
    <link rel="stylesheet" href="~/css/Navigation-with-Button.css">
    <link rel="stylesheet" href="~/css/Navigation-with-Search.css">
    <link rel="stylesheet" href="~/css/News-Cards.css">
    <link rel="stylesheet" href="~/css/Off-Canvas-Sidebar-Drawer-Navbar.css">
    <link rel="stylesheet" href="~/css/Responsive-UI-Card-02.css">
    <link rel="stylesheet" href="~/css/Right-Sidebar.css">
    <link rel="stylesheet" href="~/css/Sidebar-Menu-1.css">
    <link rel="stylesheet" href="~/css/Sidebar-Menu.css">
    <link rel="stylesheet" href="~/css/SIdebar-Responsive-2-1.css">
    <link rel="stylesheet" href="~/css/SIdebar-Responsive-2.css">
    <link rel="stylesheet" href="~/css/Sidebar-right-opening.css">
    <link rel="stylesheet" href="~/css/Social-Icons.css">
    <link rel="stylesheet" href="~/css/Soft-UI-Aside-Navbar.css">
    <link rel="stylesheet" href="~/css/Studious-sidebar.css">
    <link rel="stylesheet" href="~/css/Team-Boxed.css">
    <link rel="stylesheet" href="~/css/Vertical-Left-SideBar-by-Jigar-Mistry.css">
</head>

<body style="font-family: Cairo;">
    <nav class="navbar navbar-light navbar-expand-lg navigation-clean-button">
        <div class="container">
            <a class="navbar-brand" href="/Index">الرجوع الى الصفحة</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav me-auto">
                </ul><span class="navbar-text actions">
                    <a asp-controller="Author" asp-action="Edit" asp-route-id="@id" class="btn btn-light action-button" role="button" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">حسابي</a>
                    @{
                        if (result.Result.Succeeded)
                        {
                            <a class="btn btn-light action-button" role="button" href="/Author/Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">المستخدمين</a>

                        }
                    }
                    <a class="btn btn-light action-button" role="button" href="/Post/Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">المقالات</a>
                    @{
                        if (result.Result.Succeeded)
                        {
                            <a class="btn btn-light action-button" role="button" href="/Category/Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">الاصناف</a>

                        }
                    }
                    <a class="btn btn-light action-button" role="button" href="/AdminIndex" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;background: var(--bs-red);">الرئيسة</a>
                </span>
            </div>
        </div>
    </nav>

    <div class="container" style="font-family:Cairo;direction:rtl">
        @RenderBody()
    </div>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/bs-init-1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="~/js/Off-Canvas-Sidebar-Drawer-Navbar.js"></script>
    <script src="~/js/freelancer.js"></script>
    <script src="~/js/Off-Canvas-Sidebar-Drawer-Navbar-1.js"></script>
    <script src="~/js/Studious-sidebar.js"></script>
    <script src="~/js/bs-init.js"></script>
    <script src="~/js/chart.min.js"></script>
    <script src="~/js/Navbar---Apple.js"></script>
    <script src="~/js/Right-Sidebar.js"></script>
    <script src="~/js/Sidebar-Menu.js"></script>
    <script src="~/js/Sidebar-right-opening.js"></script>
    <script src="~/js/theme.js"></script>

    @RenderSection("Scripts", required: false)

</body>

</html>